# Generated by Django 4.2.7 on 2024-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('detail1', models.TextField(max_length=1000)),
                ('detail2', models.TextField(max_length=1000)),
                ('detail3', models.TextField(max_length=1000)),
                ('detail4', models.TextField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
